encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("wiki", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search", views.search, name="search"),
    path("random", views.random_entry, name="random"),
    path("new", views.new_entry, name = "new"),
    path("edit/<str:title>", views.edit_entry, name = "edit")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
import markdown2
from . import util
import random
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse


class NewTaskForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Title', 'style': 'width: 300px; border-radius: 10px;', 'class': 'form-control'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Content', 'style': 'border-radius: 10px; margin-top: 10px; margin-bottom: 10px;', 'class': 'form-control'}))
    
class EditTaskForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Content', 'style': 'border-radius: 10px; margin-top: 10px; margin-bottom: 10px;', 'class': 'form-control'}))

#return the home page
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

#return a page that display the content of the entry in the parameter
def entry(request, title):
    return render(request, "encyclopedia/entry.html",{
        "title": title,
        "entry": markdown2.markdown(f"{util.get_entry(title)}"),
        "exist":(util.get_entry(title)) is not None
    })

#return the content of the entry if matched, else return a list of entry that have character's matching the query
def search(request):
    input_value = request.GET.get('q')
    entry_value = util.get_entry(input_value)
    if entry_value is None:
        return render(request, "encyclopedia/search.html", {
            "entries": (util.list_entries()),
            "input": input_value
        })
    return entry(request, input_value)

#create a new entry
def new_entry(request):
    #title_value = request.POST.post('q')
    #content_value = request.POST.post('content')
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            if not util.get_entry(title):
                util.save_entry(title, content)
                return entry(request, title)
            else:
                return render(request, "encyclopedia/new.html", {
                "form": form,
                "title": title,
                "entries": util.list_entries(),
                "exist": True
            })
                
        else:
            return render(request, "encyclopedia/new.html", {
                "form": form,
                "exist": False
            })
    return render(request, "encyclopedia/new.html", {
        "form": NewTaskForm(),
        "exist": False
    })
    
#edit entry
def edit_entry(request, title):
    data = {"content": util.get_entry(title)}
    if request.method == "POST":
        form = EditTaskForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data["content"]
            util.save_entry(title, content) 
            return entry(request, title)   
        else:
            return render(request, "encyclopedia/edit.html", {
                "title": title,
                "form": EditTaskForm(initial=data),
            })
    return render(request, "encyclopedia/edit.html", {
        "title": title,
        "form": EditTaskForm(initial=data),
    })
    
#return a random encyclopedia entry
def random_entry(request):
    entry_name = random.choice(util.list_entries())
    return entry(request, entry_name)

        

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Entry
{% endblock %}

{% block body %}
    <H2>{{title}}</H2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Save">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
    {% if exist %}
        {{entry|safe}}
        <form action="{% url 'encyclopedia:edit' title %}">
            <input class="btn btn-primary" type="submit" value="Edit">
        </form>
        
    {% else %}
        <h1>Sorry, the page for "{{title}}" does not exist yet. </h1>
    {% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div class="">
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div class="">
                    <a href="{% url 'encyclopedia:new' %}">Create New Page</a>
                </div>
                <div class="">
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Entry
{% endblock %}

{% block body %}
    {% if exist %}
        <h3>{{title}} already exist.</h3>
        <ul>
            {% for entry in entries %}
                {% if title|lower in entry|lower %}
                    <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}
    
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="">
                {{ field }}
            </div>
        {% endfor %}
        <input class="btn btn-primary" type="submit" value="Create">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}
    <h2>Search Results: </h2>
    <ul>
        {% for entry in entries %}
            {% if input in entry|lower %}
                <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
            {% endif %}
        {% endfor %}
    </ul>
{% endblock %}